language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install python-coveralls
  - pip install -r requirements.txt
  - pip install .

script:
  - coverage run Tests/mainTester.py

after_success:
  - coveralls
  
branches:
  only:
  - master
