BUTTON_BACKGROUND = "white"
BUTTON_TEXTCOLOR = "black"

LABEL_TEXTCOLOR = "black"
LABEL_FONT = "Courier"
LABEL_FONT_SIZE = 10

TITLE_TEXTCOLOR = "green"
TITLE_FONT = "Courier"
TITLE_FONT_SIZE = 15
TITLE_TEXT = "Sudoku Solver"

BORDER = 10

